### ISSUE TITLE
[QUESTION]: variables to show the song name on the play/pause buutton 

### ISSUE THREAD

**Issue by mrharryhd** [XeroxDev/YTMD-StreamDeck#109]
### Consent

- [x] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Question

variables to show the song name on the play/pause buutton 
![image](https://github.com/XeroxDev/YTMD-StreamDeck/assets/148923299/8c29c361-d762-49c2-aefd-5557fda418b1)

**Comment by XeroxDev** [comment]
Hey and thank you for your suggestion! 

May I ask what the exact use case for this would be? Or why you don't (want to?) use the song info action? I'm not sure if I want to duplicate all functionalities across all actions

**Comment by mrharryhd** [comment]
i need it on the puse button becs i only have the mini streamdeck

**Comment by XeroxDev** [comment]
I'll /close this issue, because it's already implemented in another way. The thumbnail action (song info action) can be used for this, because this button also starts/pauses the current song. 

If I would implement this, we would've the exact same action twice, just with different backgrounds.

So, if you want to have a play/pause button with the title, please use the song info / thumbnail action.
