### ISSUE TITLE
[Bug]: no password input

### ISSUE THREAD

**Issue by dbones** [XeroxDev/YTMD-StreamDeck#112]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Current Behavior

hi

I cannot see the Password textbox

![image](https://github.com/XeroxDev/YTMD-StreamDeck/assets/183849/3235cf28-016e-4919-9c6d-65564b72227c)

using version 2.1

### Expected Behavior

the Play-Pause, has the method to authenticate with, which has the password box

### Steps To Reproduce

open streamdeck
download app from store
drag play-pause onto a streamdeck tile
there is no password box above the action textbox

### OS

Windows

### OS Version

11

### Plugin Version

v2.1.0

### YTMDesktop Version

v1.13

### How did you download the software?

Elgato Store

### Anything else?

cannot download 2 the windows app, as its been removed from Github

**Comment by XeroxDev** [comment]
Hello!

V2 of the plugin only supports v2 of the YTMDesktop application.

You've to either upgrade the application (more information about that are available on my discord server in the information channel) or downgrade the plugin to [v1.7.0](https://github.com/XeroxDev/YTMD-StreamDeck/releases/tag/v1.7.0)

I'll /close this issue because I think these information should resolve your issue. Shouldn't it be the case, feel free to re-open it or join the discord server to ask for more help.
