### ISSUE TITLE
[QUESTION]: <title>

### ISSUE THREAD

**Issue by raydanelgato** [XeroxDev/YTMD-StreamDeck#129]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Question

Como faço para utilizar meu YouTube music na minha area de trabalho stream deck, eu fiz dowload porem da erro para rodar

**Comment by XeroxDev** [comment]
Sadly I can't read or understand Portuguese, which is why I had to translate it (please use the English language in the future, to get better support)

translated with Google translate
> How do I use my YouTube music on my desktop stream deck, I downloaded it but it gives me an error to run

Please use the following [guide](https://help.xeroxdev.de/en/stream-deck/ytmd/home) (the [how to use](https://help.xeroxdev.de/en/stream-deck/ytmd/home#h-5-how-to-use-it) section, to be precise) on how to use the plugin.

This should answer all your questions. 

I'll /close this ticket for now. Should you still need any further help, feel free to re-open it.
