### ISSUE TITLE
[QUESTION]: <title>Updated But...

### ISSUE THREAD

**Issue by Freaker013** [XeroxDev/YTMD-StreamDeck#138]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Question

I have updated streamdeck, youtube desktop app, plugin....everything....why wont it Authorize? authorization requests are disabled? well who the F authorized that? sure as hell wasnt me. if it works(which it use to) then i dont mess with it, but when it stop working because of an update that then changes MY authorizing request that makes no sense. Stop having updates that BREAK the F-ing PLUGIN!!!

**Comment by XeroxDev** [comment]
Hello,

Thank you for bringing this issue to my attention. I apologize for any inconvenience you’ve experienced.

The recent major update to the YouTube Music Desktop App necessitated significant changes in communication and authorization protocols. Unfortunately, this required me to update the plugin to ensure it remained functional. While I strive to minimize disruptions and breaking changes, this particular update was unavoidable to keep the plugin operational.

For guidance on the new authorization process and setup, please refer to the [How to use it?](https://help.xeroxdev.de/en/stream-deck/ytmd/home#h-5-how-to-use-it) section on the Help Desk Page.

---

**Important Note:**

I kindly ask that you maintain a civil and respectful tone when communicating here or on any related platforms. As the plugin developer, I am dedicated to providing the best possible experience for users, but I do not control the YouTube Music Desktop App itself. The entire team, including those on the YTMDesktop side, is working hard to deliver a reliable service in the long term.

Please be aware that continued disrespectful behavior will not be tolerated. If you choose to disregard this request, I will have no choice but to block you and revoke your access to support across all my projects.

*Side Note: The latest versions, corresponds to version 2.x, which, under semantic versioning (semver) conventions, marks it as the first major breaking change in the plugin's history.*

For context, here are the recent releases:

- **2.0.0** (2024-02-12)
- **2.1.0** (2024-02-14)
- **2.1.1** (2024-06-06)

Given that today is 2024-08-29, ample time has passed since these releases. The changelog for v2.0.0 also clearly detailed the changes made, including the breaking changes and so did the guides/wiki change to reflect how everything works.

Thank you for understanding. 

I'll /close this ticket now.
