### ISSUE TITLE
[FEATURE]: Save Track Info to files for stream display

### ISSUE THREAD

**Issue by CatbotTsumi** [XeroxDev/YTMD-StreamDeck#49]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Feature

Currently theres not really a good way out there to display YTM track info on streams. But it seems you already have the info needed. It would be really nice to have 4 filepath fields in the Track Info button to have it save the Track Name, Artist, Album, and Album art, all in their own files, which can then be used in streams!

**Comment by XeroxDev** [comment]
Hey. I don't know if this is fitting into an StreamDeck plugin. But, if you wish, I could create a standalone tool / application for it. 

Maybe you even have a few more ideas, what I could put into it, if it should be file based, a browser source or even a desktop application.

**Comment by CatbotTsumi** [comment]
I thought about this, especially with the Track Info button not having any function other than visually. 
Streamers already have to launch a ton of programs and adding yet another program to launch and capture is undesirable. I understand it doesnt add much to the streamdeck side of things, but consider that the main audience of Stream deck is Streamers. And the YTMD Streamdeck plugin's audience is streamdeck's users who use YTMD, so I'd say it might fit more than you initially think. I know it would be incredibly useful to have it available. 
The files would be optional, where if you leave the filepath textfield blank, it doesnt do it.

**Comment by XeroxDev** [comment]
Okay. I'll add this feature for the upcoming release!

**Comment by XeroxDev** [comment]
Hey. It's me again and I've bad news.

This feature can't be added. This is due to the restrictions / lack of support from Elgato. I would have to rewrite the whole plugin in another language.

You have to open a [feature request](https://github.com/ytmdesktop/ytmdesktop/issues/new?assignees=&labels=&template=FEATURE-REQUEST.yml&title=%3Ctitle%3E) at the ytmdesktop github (just press the link) and hope they'll add it.

As long they don't add it, I'll attach you the workaround I'm using. I've developed in the past a local web page (which just have to be added as browser source. No need to start something). The only downside is: If you don't know HTML/CSS/JS, you can't really customize it, but I should've made it a bit universal (see screenshot).

![4c63](https://user-images.githubusercontent.com/10864620/163728552-89789302-2b50-4f81-9ce8-7b4e87e67414.png)

The (black) background means transparent and the padding above the information is for spectralizer.

[Download - obs-ytmd.zip](https://github.com/XeroxDev/YTMD-StreamDeck/files/8502257/obs-ytmd.zip)

I also close this issue (you can still respond to it)
