### ISSUE TITLE
[FEATURE]: Possible to add a "Play Url" like the spotify plugin?

### ISSUE THREAD

**Issue by NitroBTW** [XeroxDev/YTMD-StreamDeck#61]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Feature

The feature would be a button that you can assign the Url of a song/video or playlist that you can press to immediately swap to that specific song/video or playlist

**Comment by XeroxDev** [comment]
Hey. Thank you for your request.

I'll check what I can do, but can't promise anything (especially due to the Holiday season in my country).

But can you give me some more information on how you would like it? Just a field where you post a link to a YouTube **Music** Video / Playlist? Or do you really mean Videos/Playlists from youtube.com?

**Comment by NitroBTW** [comment]
> But can you give me some more information on how you would like it? Just a field where you post a link to a YouTube **Music** Video / Playlist? Or do you really mean Videos/Playlists from youtube.com?

Yes you would have a field to enter a Youtube Music Video / Playlist link and then when you press the button it would start playing that Video/Playlist in Youtube Music immediately

(sorry that I didnt make it clear the first time)

**Comment by XeroxDev** [comment]
Hey! I'm currently working on the V2 support and tried to implement your suggested feature.

Sadly I've to inform you, that it's not possible, to implement this in the current plugin architecture. I've tried it in multiple ways but it seems no matter what I try, I can't use custom URI schemes (the only thing YTMDesktop supports to do something like that). Elgato seems to block it and like mentioned before, YTMDestkop, even in V2, doesn't support such things through their API.

That's why I've considered to /close this issue for now. I'll re-investigate it in the future to look if support gets added.
