### ISSUE TITLE
Youtube Music desktop app doesn't have an option for integration. 

### ISSUE THREAD

**Issue by OGIBE** [XeroxDev/YTMD-StreamDeck#69]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Question

You're "How to use?" is horribly ill prepared to inform people on how to use this plugin. The settings on YTMD app have no such option as "Enable companion server" or "Remote control".

**Comment by XeroxDev** [comment]
Hey!

Did you install YTMDesktop like mentioned in the "How to use it" section? Because what you're explaining sounds like, that you're using the wrong application. You probably just installed the YouTube Music PWA (Chrome App) which is NOT supported, instead of the one mentioned in the "How to use it" section.

/label "+More details required"

**Comment by XeroxDev** [comment]
Small update: I did you a favor and added a video tutorial to the README (Video by [Vahyking](https://www.youtube.com/@Vahyking) Thank you!). 

I'll /close this issue now. If something is still not working related to this, feel free to reopen it.
