### ISSUE TITLE
[FEATURE]: Track Info button to act as play/pause or be selectable

### ISSUE THREAD

**Issue by gmerck** [XeroxDev/YTMD-StreamDeck#70]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Feature

Add a function option to the Track Info button.  In my experience, and using the YTMD app, pressing the info duplicates the player in a browser window starting a second instance.  Seems like it would be more functional to have the Track Info button act as play/pause by default.  Maybe I'm missing something, but if there were more options for action to select, that's one less button I have to use if I can avoid a separate play/pause button.

### Solution

Seems like it would be more functional to have the Track Info button act as play/pause by default.  Maybe I'm missing something, but if there were more options for action to select, that's one less button I have to use if I can avoid a separate play/pause button.

**Comment by XeroxDev** [comment]
Hey! Thank you for the request. I'll consider this request. I initially thought about this action as "read/view only" but then decided instead of just showing the information, to open the track in the browser, so the user can easier share or bookmark the link. But it's a good idea to also add this functionality or at least a option / choice.

I'll set the issue to "On Hold" while the decision-making
/label +good +low +hold

**Comment by j0dan** [comment]
Coming from Spotify (and BarRaider's wonderful plugin) and really missed this. It feels natural to have the album art as the play/pause button to me.

**Comment by XeroxDev** [comment]
Small update: it will be implemented when I upgrade the plugin to YTMDesktop v2.
